version: '3.7'  # Use a specific minor version for better compatibility

networks:
  dns-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"  # Only required if you're using Pi-hole as a DHCP server
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Asia/Kolkata'  # Use a more specific time zone string
      WEBPASSWORD: 'mypass'  # Set a password for the Pi-hole admin interface
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
    networks:
      dns-network:
        ipv4_address: 10.0.0.5
    volumes:
      - ./dnscli/scripts:/scripts

  dns-client-1:
    build:
      context: ./dnscli
    container_name: dns-client-1
    command: tail -f /dev/null  # Keeps the container running
    depends_on:
      - pihole
    networks:
      dns-network:
        ipv4_address: 10.0.0.2
    volumes:
      - ./dnscli/scripts:/scripts

  dns-client-2:
    build:
      context: ./dnscli
    container_name: dns-client-2
    command: tail -f /dev/null  # Keeps the container running
    depends_on:
      - pihole
    networks:
      dns-network:
        ipv4_address: 10.0.0.3
    volumes:
      - ./dnscli/scripts:/scripts

